collections:
  authors:
    output: true

defaults:
- scope:
    path: ""
    type: "authors"
  values:
    layout: "author"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
  values:
    layout: "default"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

# Todas las web tienen el layout "padre" default
# Los posts además tienen el layout "posts"
# Los author tienen author